
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo
  namespace: default
  labels:
    app/group: fastapi-demo
    language: python
    app/profile: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app/group: fastapi-demo
      language: python
      app/profile: prod
  template:
    metadata:
      labels:
        app/group: fastapi-demo
        language: python
        app/profile: prod
    spec:
      containers:
      - name: server
        image: pydemia/fastapi-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 5678
        args:
        - gunicorn
        - fastapi_app.main:app
        - --preload
        - -k=uvicorn.workers.UvicornWorker
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "8000"
          - name: DEBUG_PORT
            value: "5678"
        resources:
          requests:
            memory: "3G"
            cpu: "500m"
          limits:
            memory: "3G"
            cpu: "1"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
  namespace: default
  labels:
    app/group: fastapi-demo
    language: python
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app/group: fastapi-demo
    language: python